### ISSUE TITLE
`jest-fetch-mock` import error in react-native integration

### ISSUE THREAD

**Issue by jayzes** [honeybadger-io/honeybadger-js#1278]
## What are the steps to reproduce this issue?
1. Install the React Native integration following the instructions here: https://docs.honeybadger.io/lib/javascript/integration/react-native/
2. Attempt to run the app in dev mode (e.g. using `expo run ios`)

## What happens?
A compilation error occurs: 

```
Unable to resolve "jest-fetch-mock" from "node_modules/@honeybadger-io/react-native/dist/index.js"
```

## What were you expecting to happen?
No error

## Any logs, error output, etc?
Just the one above.

## Any other comments?
From what I can tell, it seems like this was a regression introduced in https://github.com/honeybadger-io/honeybadger-js/pull/1241. Happy to take a stab at pulling out that import to see if it solves the issue. I experienced the issue with version 6.3.2 of the `@honeybadger-io/react-native` library, but if I downgrade to 6.1.1 everything is totally fine.

## What versions are you using?
**Operating System:** MacOS 14.2.1
**Package Name:** @honeybadger-io/react-native
**Package Version:** 6.3.2
**Browser Version:** N/A

**Comment by subzero10** [comment]
Hello @jayzes, thanks for submitting an issue! I'll take a look at this asap.

Happy New Year!

**Comment by subzero10** [comment]
Hey @jayzes, this should be fixed with `v6.3.3`!
