### ISSUE TITLE
Version 5.1.1 is broken on Next.js

### ISSUE THREAD

**Issue by bymoe** [honeybadger-io/honeybadger-js#1020]
## What are the steps to reproduce this issue?
1. Install both `@honeybadger-io/react` & `@honeybadger-io/js` @ v `5.1.1`
2. Try to deploy to something like vercel or even locally
3. You'll get `TypeError: _window.addEventListener is not a function` 

## What happens?
I am getting `TypeError: _window.addEventListener is not a function` after upgrading to v5

## What were you expecting to happen?
To support SSR? Not sure why it was working fine before.

## Any logs, error output, etc?
`TypeError: _window.addEventListener is not a function`

## What versions are you using?
**Operating System:** Mac
**Package Name:** `@honeybadger-io/react` & `@honeybadger-io/js` @ v `5.1.1`
**Package Version:** 5.1.1

![Screenshot from 2023-02-13 20-37-40](https://user-images.githubusercontent.com/20565199/218531279-5c0d753b-c8c8-4c49-9f4f-a0615fea6000.png)

**Comment by bymoe** [comment]
Thanks @subzero10 :+1: 

Also another thing I'd like to mention is the docs are not very clear about which is the best way to integrate or even to upgrade from version to version. 
On the previous version `@honeybadger-io/react": "^2.0.1` it took me 5min to setup. Now it just for some reason 10x more complicated.
The docs for example have multiple integration ways:
e.g. latest [React docs](https://docs.honeybadger.io/lib/javascript/integration/react/) tells you to install `@honeybadger-io/js @honeybadger-io/react`. But the [Next.js example](https://github.com/honeybadger-io/nextjs-with-honeybadger) tells to install `"@honeybadger-io/js"  "@honeybadger-io/webpack"` is the  `@honeybadger-io/react` deprecated ? Since nothing indicates that in the [package readme](https://www.npmjs.com/package/@honeybadger-io/react). Is Next.js not considered part of "React" docs? Just not sure, It's a bit confusing! 

Thanks!

**Comment by subzero10** [comment]
Hey @bymoe, apologies for all the trouble caused!

> Also another thing I'd like to mention is the docs are not very clear about which is the best way to integrate or even to upgrade from version to version.

We use lerna versioning and keep all the versions aligned, so sometimes a package may get a major version bump, but it doesn't necessarily mean that there are breaking changes. In any case, I've taken note of this and we will more communicative with version upgrades.

> The docs for example have multiple integration ways:
e.g. latest [React docs](https://docs.honeybadger.io/lib/javascript/integration/react/) tells you to install @honeybadger-io/js @honeybadger-io/react. But the [Next.js example](https://github.com/honeybadger-io/nextjs-with-honeybadger) tells to install "@honeybadger-io/js"  "@honeybadger-io/webpack" is the @honeybadger-io/react deprecated ? Since nothing indicates that in the [package readme](https://www.npmjs.com/package/@honeybadger-io/react). Is Next.js not considered part of "React" docs? Just not sure, It's a bit confusing!

We have a ticket to internally work on our Next.js documentation, because it can get tricky.
The nextjs example repo was created to assist with source map uploads and configuration, which is done using the `@honeybadger-io/webpack` package. `@honeybadger-io/react` is not deprecated and you may use that one for your nextjs projects. [We will update our nextjs example repo to remove this confusion](https://github.com/honeybadger-io/nextjs-with-honeybadger/issues/11).

> Also, previously with v2 @honeybadger-io/react it was working perfectly for SSR/Next and on the node.js without any extra [overhead setup](https://github.com/honeybadger-io/nextjs-with-honeybadger/blob/master/pages/_app.js#L13) that's still errors. not sure what changes.

The link you are referencing is a current workaround we have to make **source maps** work, but it's not yet on the official docs because it does not work with Next.js apps deployed on Vercel (but it works with Heroku). If you are not uploading source maps, you may not need this configuration.

I'm currently investigating the issue with the broken SSR, we will get that sorted out soon.
Finally, I created an issue to come up with a [nextjs dedicated package](https://github.com/honeybadger-io/honeybadger-js/issues/1023); that should help simplifying things.

**Comment by subzero10** [comment]
Hey @bymoe, a fix was just released!
Can you please try with `@honeybadger-io/js@5.1.1` and `@honeybadger-io/react@5.1.3`?
